services:

  
  db:
    image: postgres
    container_name: postgresDB
    restart: always
    environment:
      - POSTGRES_DB=${APP_CONFIG_DB_NAME}
      - POSTGRES_USER=${APP_CONFIG_DB_USER}
      - POSTGRES_PASSWORD=${APP_CONFIG_DB_PASSWORD}
    
    ports:
      - "5432:5432"

  api:
      build: ./Backend
      ports:
        - "5010:5010"
      depends_on:
        - db


  adminer:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE='False' 
    ports: 
      - "5050:80"

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${RD_PASSWORD}
      - REDIS_USER=${RD_USER}
      - REDIS_USER_PASSWORD=${RD_USER_PASSWORD}

    ports:
      - "6380:6379"  
